### ISSUE TITLE
Doc polishing tracking issue

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#1151]
This is for @blakehatch and me to track which files we consider "polished".

- [ ] config/basic-configs.mdx
- [ ] config/production-config.mdx
- [ ] contribute/bazel.mdx
- [ ] contribute/cargo.mdx
- [ ] contribute/nix.mdx
- [ ] deployment-examples/on-prem-overview.mdx
- [ ] explanations/architecture.mdx
- [ ] explanations/history.mdx
- [ ] faq/caching.mdx
- [ ] faq/cost.mdx
- [ ] faq/hermeticity.mdx
- [ ] faq/lre.mdx
- [ ] faq/nix.mdx
- [ ] faq/remote-execution.mdx
- [ ] faq/rust.mdx
- [ ] faq/toolchains.mdx
- [ ] index.mdx
- [ ] introduction/contributors.mdx
- [ ] introduction/non-bre.mdx
- [ ] introduction/on-prem.mdx
- [ ] nativelink-cloud/
- [ ] nativelink-cloud/bazel.mdx
- [ ] nativelink-cloud/pants.mdx
- [ ] nativelink-cloud/reclient.mdx
- [ ] reference/glossary.mdx
